In [2]:
import numpy as np

In [3]:
vocabulary = np.load('./tokens/vocab.npy')

In [4]:
print('Vocabulary size:', len(vocabulary))
print('Vocabulary:', vocabulary[:10])
print('type:', type(vocabulary))

Vocabulary size: 1000
Vocabulary: ['' '[UNK]' 'obesidad' 'enfermedad' 'asma' 'hipotiroidismo'
 'asma_no_especificada' 'dislipidemia' 'hipertensión_arterial'
 'falla_respiratoria']
type: <class 'numpy.ndarray'>


In [5]:
X_train = np.load('./tokens/X_train.npy')

In [6]:
print("X_train shape:", X_train.shape)
print("ten first elements of X_train:", X_train[:10])
print("type:", type(X_train))

X_train shape: (306, 730)
ten first elements of X_train: [[173   2  63 ...   0   0   0]
 [ 19  79  15 ...   0   0   0]
 [ 86   3 122 ...   0   0   0]
 ...
 [850 850 444 ...   0   0   0]
 [134  59   1 ...   0   0   0]
 [882 201 882 ...   0   0   0]]
type: <class 'numpy.ndarray'>


In [7]:
y_train = np.load('./tokens/y_train.npy')
print("y_train shape:", y_train.shape)
print("ten first elements of y_train:", y_train[:10])
print("type:", type(y_train))

y_train shape: (306,)
ten first elements of y_train: [0 1 1 0 0 1 1 0 1 0]
type: <class 'numpy.ndarray'>


In [8]:
#print(X_train[0])
X_seq = []
patient_n = 0
for i in range(len(X_train[patient_n])):
    number = X_train[patient_n][i]
    print('number:', number)
    enf = vocabulary[number]
    X_seq.append(enf)
print(X_seq)
print('len(X_seq):', len(X_seq))

number: 173
number: 2
number: 63
number: 39
number: 19
number: 173
number: 2
number: 8
number: 173
number: 173
number: 173
number: 173
number: 173
number: 63
number: 180
number: 39
number: 19
number: 173
number: 158
number: 1
number: 1
number: 173
number: 173
number: 173
number: 173
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number: 0
number

In [9]:
# Paso 1: Importar las librerías necesarias
import tensorflow as tf

2025-05-12 14:00:24.288604: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-12 14:00:24.378704: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-12 14:00:24.782484: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-05-12 14:00:24.782553: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-05-12 14:00:24.785077: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to regi

In [10]:
# Paso 3: Cargar el modelo .h5 (ajusta la ruta si es necesario)
# Por ejemplo: '/content/drive/MyDrive/modelo.h5'
ruta_modelo = './lstm_v66.h5'
modelo = tf.keras.models.load_model(ruta_modelo)

In [11]:
# Paso 4: Mostrar resumen del modelo (incluye nombre, forma y parámetros de cada capa)
modelo.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 730, 200)          200000    
                                                                 
 bidirectional_1 (Bidirecti  (None, 128)               135680    
 onal)                                                           
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 344001 (1.31 MB)
Trainable params: 344001 (1.31 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
# Paso 5 (opcional): Listar solo los nombres de las capas
for capa in modelo.layers:
    print("Nombre de la capa:", capa.name)

Nombre de la capa: embedding_1
Nombre de la capa: bidirectional_1
Nombre de la capa: dense_2
Nombre de la capa: dense_3


In [13]:
print("X_sample shape:", X_train.shape)
print(type(X_train))

X_sample shape: (306, 730)
<class 'numpy.ndarray'>


In [13]:
print("X_sample shape:", X_train[0].shape)
print(X_train[0])

X_sample shape: (730,)
[173   2  63  39  19 173   2   8 173 173 173 173 173  63 180  39  19 173
 158   1   1 173 173 173 173   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0

In [ ]:
X_sample = X_train[:1, :]
print("X_sample shape:", X_sample.shape)
print(type(X_sample))

In [ ]:
print(X_sample)

In [14]:
# 4. Seleccionar la capa desde la cual calcular el gradiente (embedding)
embedding_layer = modelo.get_layer('embedding_1')

In [15]:
from alibi.explainers import IntegratedGradients
# 5. Inicializar IntegratedGradients con el modelo y capa de entrada
ig = IntegratedGradients(modelo, layer=embedding_layer, n_steps=50, method='gausslegendre', internal_batch_size=1)

/home/pajaro/anaconda3/envs/ali_env_v1/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-05-12 14:00:53,635	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.


In [ ]:
# 6. Ejecutar IG
explanation = ig.explain(
    X_sample,    
    target=0,    
)

In [ ]:
# 7. Visualizar las atribuciones
attributions = explanation.attributions[0]  # (100, embedding_dim)
token_importances = np.sum(attributions, axis=-1)  # suma por embedding

In [ ]:
print(attributions.shape)
print(type(attributions))

In [ ]:
print(token_importances.shape)
print(type(token_importances))

In [ ]:
print(token_importances)

In [ ]:
y_pos = np.arange(len(token_importances))
print(len(y_pos))

In [ ]:
# Asegurarse de que token_importances es un array 1D
token_imp = np.array(token_importances).flatten()
print(token_imp.shape)
print(len(token_imp))


In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10, 10))
ax.barh(X_seq, token_imp)
ax.set_xlabel('Importancia')
ax.set_title('Atribuciones de Integrated Gradients')
plt.show()

In [ ]:
print(X_seq)

In [ ]:
phe_uniques = set(X_seq)
print(phe_uniques)
print(len(phe_uniques))

In [ ]:
predictions = modelo(X_sample).numpy().argmax(axis=1)

In [ ]:
print("Predicción:", predictions)
print(type(predictions))

In [ ]:
# 6. Ejecutar IG
explanation = ig.explain(
    X_sample,    
    target=predictions,    
)

In [ ]:
# 7. Visualizar las atribuciones
attributions = explanation.attributions[0]  # (100, embedding_dim)
token_importances = np.sum(attributions, axis=-1)  # suma por embedding
# Asegurarse de que token_importances es un array 1D
token_imp = np.array(token_importances).flatten()
fig, ax = plt.subplots(figsize=(10, 10))
ax.barh(X_seq, token_imp)
ax.set_xlabel('Importancia')
ax.set_title('Atribuciones de Integrated Gradients')
plt.show()

In [16]:
X_test = np.load('./tokens/X_test.npy')
print("X_test shape:", X_test.shape)
print("ten first elements of X_test:", X_test[:10])
print("type:", type(X_test))

X_test shape: (76, 730)
ten first elements of X_test: [[217   3  16 ...   0   0   0]
 [134 107 134 ...   0   0   0]
 [113  59 664 ...   0   0   0]
 ...
 [102   2   2 ...   0   0   0]
 [ 76  99  99 ...   0   0   0]
 [129 258 129 ...   0   0   0]]
type: <class 'numpy.ndarray'>


In [17]:
y_test = np.load('./tokens/y_test.npy')
print("y_test shape:", y_test.shape)
print("ten first elements of y_test:", y_test[:10])
print("type:", type(y_test))

y_test shape: (76,)
ten first elements of y_test: [0 0 1 1 0 1 0 1 1 1]
type: <class 'numpy.ndarray'>


In [18]:
predictions = modelo(X_test).numpy().argmax(axis=1)

In [19]:
# 6. Ejecutar IG
explanation = ig.explain(
    X_test,    
    target=0,    
)

: 

In [ ]:
# 7. Visualizar las atribuciones
attributions = explanation.attributions[0]  # (100, embedding_dim)
token_importances = np.sum(attributions, axis=-1)  # suma por embedding
# Asegurarse de que token_importances es un array 1D
token_imp = np.array(token_importances).flatten()
fig, ax = plt.subplots(figsize=(10, 10))
ax.barh(X_seq, token_imp)
ax.set_xlabel('Importancia')
ax.set_title('Atribuciones de Integrated Gradients')
plt.show()